# Generated by Django 2.1.1 on 2018-10-13 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Manager')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='trade_date',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='active_date',
            field=models.DateTimeField(verbose_name='Active Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Manager'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='strategy',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Instrument'),
        ),
        migrations.AddField(
            model_name='position',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio'),
        ),
        migrations.AddField(
            model_name='position',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Instrument'),
        ),
    ]
