# Generated by Django 2.1.1 on 2018-10-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181013_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='symbol',
            new_name='instrument',
        ),
    ]
