# Generated by Django 2.1.1 on 2018-10-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181013_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='symbol',
            new_name='instrument',
        ),
    ]
