# Generated by Django 2.1.1 on 2018-10-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20181013_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='strategy',
            field=models.CharField(max_length=200),
        ),
    ]
